### ISSUE TITLE
gulp v5 compatibility

### ISSUE THREAD

**Issue by bytestream** [sindresorhus/gulp-tar#31]
```bash
$ npx gulp --version
CLI version: 3.0.0
Local version: 5.0.0
```

```js
gulp.task('foo', gulp.series(function () {
    return gulp.src(['./archive.tar'])
        .pipe(untar());
}));
```

```
[21:05:09] Error: invalid tar file
    at Parse._startEntry (/node_modules/tar/lib/parse.js:150:13)
    at Parse._process (/node_modules/tar/lib/parse.js:132:12)
    at BlockStream.<anonymous> (/node_modules/tar/lib/parse.js:48:8)
    at BlockStream.emit (node:events:514:28)
    at BlockStream.emit (node:domain:489:12)
    at BlockStream._emitChunk (/node_modules/block-stream/block-stream.js:145:10)
    at BlockStream.write (/node_modules/block-stream/block-stream.js:45:10)
    at Parse.write (/node_modules/tar/lib/parse.js:82:23)
    at MultiStream.ondata (node:internal/streams/readable:766:22)
    at MultiStream.emit (node:events:514:28)
    at MultiStream.emit (node:domain:552:15)
    at MultiStream.Readable.read (node:internal/streams/readable:539:10)
    at flow (node:internal/streams/readable:1023:34)
    at resume_ (node:internal/streams/readable:1004:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

```

**Comment by bytestream** [comment]
Sorry - completely wrong page! 🙄
